FROM python:3.11-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

COPY . /app

RUN pip install --upgrade pip

# fallback default (each service overrides entrypoint)
CMD ["python", "-m", "app"]
